module.exports = {
  apps: [
    {
      name: 'hmnl-app',
      script: 'npx',
      args: 'vite',
      cwd: __dirname,
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'development',
        PORT: 5173,
      },
      error_file: './logs/pm2-error.log',
      out_file: './logs/pm2-out.log',
      pid_file: './logs/pm2.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      time: true,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 3000,
      kill_timeout: 5000,
      wait_ready: true,
      listen_timeout: 10000,
    },
  ],
};
