module.exports = {
  apps: [
    {
      name: 'miaoda-react-admin',
      script: 'pnpm',
      args: 'run dev',
      cwd: '/data/hmnl3n/app-883oyd7kz475 - 副本 (2)',
      interpreter: 'none',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 5173,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 5173,
      },
      error_file: './logs/pm2-error.log',
      out_file: './logs/pm2-out.log',
      log_file: './logs/pm2-combined.log',
      time: true,
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 1000,
      kill_timeout: 5000,
      listen_timeout: 3000,
      wait_ready: false,
      shutdown_with_message: false,
    },
  ],
};
